version: '3'
services:
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo"
  monitoring:
    environment:
      - REDIS_HOST=redis:6379
      - MONGO_HOST=mongo:27017
    build: 
      context: .
      dockerfile: monitoring.Dockerfile
    depends_on:
      - redis
      - mongo
  consumer:
    environment:
      - REDIS_HOST=redis:6379
      - MONGO_HOST=mongo:27017
    build:
      context: .
      dockerfile: consumer.Dockerfile
    depends_on:
      - redis
      - mongo
  api:
    environment:
      - MONGO_HOST=mongo:27017
      - REDIS_HOST=redis:6379
      - API_PORT=80
    build:
      context: .
      dockerfile: api.Dockerfile
    depends_on:
      - redis
      - mongo